apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demojob
spec:
  entrypoint: run-job01
  arguments:
    parameters:
      - name: Org
        value: "TN-1234"
      - name: Program
        value: "555"
      - name: ErrorRate
        value: 75
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
  templates:
    - name: run-job01
      inputs:
        parameters:
          - name: Org
          - name: Program
          - name: ErrorRate
            default: 0
      retryStrategy:
        limit: 10
      container:
        image: k3d-demo-cronworkflow:5111/demo-cronworkflow-job01
        command: ["./job.sh"]
        args:
          - "{{inputs.parameters.Org}}"
          - "{{inputs.parameters.Program}}"
          - "{{inputs.parameters.ErrorRate}}"
