apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demojob-pedrapreta-
spec:
  entrypoint: demojob
  workflowTemplateRef:
      name: demojob-template
  arguments:
    parameters:
      - name: Org
        value: "Banco-PedraPreta"
      - name: Program
        value: "771"
      - name: ErrorRate
        value: 70 # Fail 70% of the runs
