apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demojob-
spec:
  entrypoint: demojob
  workflowTemplateRef:
      name: demojob-template
  arguments:
    parameters:
      - name: Org
        value: "TN-DEMO-ORG-0001"
      - name: Program
        value: "777"
